insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (1, 49143, 'Gislason-Douglas', 21, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (2, 29859, 'Sipes, Breitenberg and Greenholt', 70, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (3, 84411, 'Purdy Group', 21, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (4, 51507, 'Ernser, Kohler and Witting', 48, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (5, 42058, 'Batz Inc', 49, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (6, 80044, 'Heathcote, Orn and Ruecker', 30, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (7, 92680, 'Swift, Schuppe and Hodkiewicz', 1, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (8, 28437, 'Stroman, Kovacek and Bode', 67, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (9, 38233, 'Kshlerin, Botsford and Orn', 41, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (10, 45151, 'Batz, Graham and King', 3, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (11, 46863, 'Rippin, Mitchell and Padberg', 83, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (12, 58745, 'Leffler and Sons', 4, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (13, 23785, 'Boehm Inc', 23, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (14, 91081, 'Shanahan Inc', 94, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (15, 84087, 'Smitham, Swaniawski and Boehm', 27, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (16, 60402, 'Spinka, Watsica and Price', 10, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (17, 33644, 'Bogan, Bednar and Dare', 64, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (18, 54027, 'Zieme-Hand', 28, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (19, 17221, 'McClure Inc', 37, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (20, 79957, 'Heller-Fay', 24, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (21, 14265, 'Heathcote, Rempel and Greenfelder', 64, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (22, 40762, 'Konopelski, Haley and Reichel', 53, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (23, 77320, 'Barrows-Kertzmann', 29, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (24, 62210, 'Schimmel-Smith', 38, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (25, 69827, 'Emmerich, Oberbrunner and Pollich', 82, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (26, 22913, 'Rath-Schuster', 89, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (27, 83823, 'Stehr and Sons', 18, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (28, 13324, 'Labadie-Marks', 68, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (29, 52075, 'Goodwin, Legros and Boyle', 19, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (30, 11570, 'Denesik, Bahringer and Stracke', 67, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (31, 62427, 'Russel, Bosco and Baumbach', 40, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (32, 13938, 'Thiel, Gaylord and Sporer', 52, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (33, 86357, 'Becker-West', 45, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (34, 63405, 'Larson-Pollich', 36, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (35, 83786, 'Ortiz, Volkman and Keebler', 1, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (36, 79875, 'Nader Inc', 53, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (37, 44903, 'Zemlak and Sons', 22, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (38, 71001, 'Collier-Windler', 20, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (39, 75308, 'Buckridge, O''Keefe and Barrows', 76, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (40, 88407, 'Hegmann LLC', 20, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (41, 25619, 'Greenholt-Ledner', 78, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (42, 48673, 'McKenzie, Herman and Heller', 69, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (43, 22433, 'Cartwright-Nikolaus', 69, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (44, 37695, 'Gaylord, Bechtelar and Ankunding', 61, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (45, 64079, 'Douglas, Langworth and Robel', 43, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (46, 53329, 'Gaylord Group', 39, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (47, 48302, 'Upton LLC', 86, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (48, 11497, 'Hyatt Group', 9, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (49, 29603, 'Ebert-Russel', 22, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (50, 30943, 'Schiller Inc', 100, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (51, 96847, 'Gleichner, Donnelly and Schoen', 12, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (52, 96714, 'Lockman, Kulas and Wisoky', 78, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (53, 43253, 'Lowe, Fisher and Streich', 82, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (54, 74597, 'Gerhold Group', 4, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (55, 60292, 'Kling, Bahringer and Langworth', 94, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (56, 38967, 'Mayer Inc', 70, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (57, 15130, 'Walter-Green', 60, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (58, 69968, 'Mitchell and Sons', 30, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (59, 30497, 'Schroeder, Labadie and Boehm', 98, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (60, 95848, 'Schneider-Weber', 38, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (61, 52872, 'Cole, Tromp and Cormier', 9, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (62, 24465, 'Raynor Inc', 92, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (63, 23671, 'O''Conner-Ebert', 7, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (64, 87699, 'Moore Group', 99, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (65, 75562, 'Jaskolski and Sons', 31, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (66, 89104, 'Hamill-Hoppe', 24, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (67, 41269, 'Kuhn, Boyle and Oberbrunner', 50, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (68, 59376, 'Fritsch, Heidenreich and Smith', 59, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (69, 48123, 'McLaughlin-Olson', 67, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (70, 65093, 'Hettinger Group', 51, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (71, 84096, 'Vandervort-Funk', 15, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (72, 94890, 'Roob-Monahan', 94, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (73, 39174, 'Buckridge-Yost', 22, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (74, 15069, 'Simonis-Kling', 61, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (75, 65455, 'McClure, Carter and Wiza', 51, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (76, 68151, 'Reinger-Hilpert', 1, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (77, 92289, 'Schulist-Simonis', 86, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (78, 25200, 'Mertz-Price', 59, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (79, 13549, 'Rosenbaum-Olson', 1, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (80, 50648, 'Hettinger LLC', 63, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (81, 51742, 'Trantow-Brekke', 25, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (82, 85427, 'McCullough LLC', 76, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (83, 17981, 'O''Connell, Kling and Hagenes', 7, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (84, 75912, 'Goodwin Inc', 20, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (85, 66687, 'Stroman-Altenwerth', 55, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (86, 36312, 'Pagac, Durgan and Reichert', 5, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (87, 70701, 'Gulgowski, Jast and Ullrich', 25, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (88, 29316, 'Von Group', 69, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (89, 57548, 'Jaskolski LLC', 63, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (90, 96037, 'Wunsch, Farrell and Tromp', 27, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (91, 52166, 'Champlin and Sons', 39, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (92, 60112, 'Hilpert LLC', 74, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (93, 70301, 'Gleason, Dickinson and Ullrich', 14, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (94, 26329, 'Zieme, Abbott and Quitzon', 65, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (95, 12643, 'Zboncak Group', 47, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (96, 69020, 'Rohan Group', 64, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (97, 95589, 'Mayer-Satterfield', 16, 'COD');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (98, 33071, 'Hamill-Yundt', 41, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (99, 97135, 'Hamill Group', 26, 'Internet Banking');
insert into ctkmhethong (id, phiVC, dichvuVC, diemTichLuy, ptThanhToan) values (100, 26636, 'Effertz-Smith', 59, 'Internet Banking');
